export const GET_MEMBERS_START = 'GITHUB/GET_MEMBERS_START';
export const GET_MEMBERS_SUCCEED = 'GITHUB/GET_MEMBERS_SUCCEED';
export const GET_MEMBERS_FAIL = 'GITHUB/GET_MEMBERS_FAIL';
export const SEARCH_USER_START = 'GITHUB/SEARCH_USER_START';
export const SEARCH_USER_SUCCEED = 'GITHUB/SEARCH_USER_SUCCEED';
export const SEARCH_USER_FAIL = 'GITHUB/SEARCH_USER_FAIL';
export const CLEAR = 'GITHUB/CLEAR';
