export const ADD_MEMBERS = 'RANDOM/ADD_MEMBERS';
export const REMOVE_MEMBER = 'RANDOM/REMOVE_MEMBER';
export const START = 'RANDOM/START';
export const STOP = 'RANDOM/STOP';
export const APOINT_USER = 'RANDOM/APOINT_USER';
